### ISSUE TITLE
Graph API v2.4 Upgraded to v2.5

### ISSUE THREAD

**Issue by mgpro94** [jeduan/cordova-plugin-facebook4#560] opened 2017-09-13 07:30 UTC
hello,

i just rescived this mail:

> Your App, ‎באליפיצה‎, is currently accessing Graph API v2.4 which will reach the end of its 2-year lifetime on 09 October, 2017. We estimate 6 endpoints that ‎באליפיצה‎ calls will be impacted by this change and may stop working after the automatic upgrade push. To ensure a smooth transition, please migrate all calls to Graph API v2.5 or higher. Use the API Upgrade Tool to understand exactly how this change will impact your app.

this is the plugin fault or me using it wrong?

**Comment by Allan-Nava** [comment] 2017-09-13 09:11
Hi,

I have the same issue, how can I update the Graph API v2.4 to v2.10? 

Thx

**Comment by alssl-ross** [comment] 2017-09-13 09:37
We have the same issue.

I think it relates to the iOS Facebook Framework embedded in the plugin at plugins\cordova-plugin-facebook4\src\ios.

https://github.com/facebook/facebook-ios-sdk

**Comment by bsautel** [comment] 2017-09-13 16:33
I also received this email. I am using the latest version of the plugin (1.9.1).

For iOS, it should use the Facebook SDK version 4.22.1 (according to this [commit message](https://github.com/jeduan/cordova-plugin-facebook4/tree/3770c9c910f3627557179af4656214209c47be38/src/ios), I don't know how to see it in the framework files).

For Android, it should use the latest available version (4.+) according to the [plugin build file](https://github.com/jeduan/cordova-plugin-facebook4/blob/3770c9c910f3627557179af4656214209c47be38/plugin.xml#L63). We can see that the Maven Central repository contains [many versions after 4.4](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.facebook.android%22%20AND%20a%3A%22facebook-android-sdk%22) (4.26.0 now).

All this makes the 1.9.1 version of the plugin should not use a 4.4 version. Are the Facebook 4.4 API calls done by old versions of our application that used an old version of this plugin which relies on the Facebook SDK 4.4?

**Comment by fredgalvao** [comment] 2017-09-13 17:33
I'll close this as a duplicate of https://github.com/jeduan/cordova-plugin-facebook4/issues/518. If after reading the coments there, any of you guys think it as a different issue (basically if you confirm your app made calls to outdated api versions), feel free to provide more info and we can reopen and review it.

**Closed by fredgalvao** 2017-09-13 17:33 UTC

**Comment by nhoctanker** [comment] 2017-09-19 02:31
@fredgalvao  Do we need to update this plugin?

**Comment by fredgalvao** [comment] 2017-09-19 03:36
I don't think we **need** to.
