### ISSUE TITLE
'FBSDKCoreKit/FBSDKCoreKit.h' file not found

### ISSUE THREAD

**Issue by Buraky89** [jeduan/cordova-plugin-facebook4#847] opened 2020-01-23 14:12 UTC
Hello, I am getting an error such as "'FBSDKCoreKit/FBSDKCoreKit.h' file not found" when I do the following

$ cordova create myApp
Creating a new cordova project.
$ cd myApp/
$ cordova platform add ios
Using cordova-fetch for cordova-ios@~4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: io.cordova.hellocordova
	Name: HelloCordova
iOS project created with cordova-ios@4.5.5
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving ios@~4.5.5 into config.xml file ...
$ cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication"
Installing "cordova-plugin-facebook4" for ios
Adding cordova-plugin-facebook4 to package.json
Saved plugin info for "cordova-plugin-facebook4" to config.xml

Then I try to build it in XCode Version 11.1 (11A1027), I get the following error:

'FBSDKCoreKit/FBSDKCoreKit.h' file not found

I am using cordova-ios 4.5.5. 

I tried adding the following lines (as you can see in the second commit, in my reproduce repository)

<framework src="FBSDKCoreKit" type="podspec" spec="5.14.0" />
<framework src="FBSDKLoginKit" type="podspec" spec="5.14.0" />
<framework src="FBSDKShareKit" type="podspec" spec="5.14.0" />

Then removed and readded the ios platform. 

Then another error shows up: Module 'FBSDKCoreKit' not found FBSDKLoginButton.h

**Expected Behavior**

Project is able to be built

**Plugin version, OS, devices, etc**

Cordova version: 8.1.2 (cordova-lib@8.1.1)
Cordova-ios version: 4.5.5
XCode version: 11.1 (11A1027)

**Sample repo**

https://github.com/Buraky89/CordovaFacebookReprod

**Comment by peterpeterparker** [comment] 2020-01-23 14:13
Doc https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/ios/README.md

**Comment by Buraky89** [comment] 2020-01-23 14:15
> See doc https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/ios/README.md

I tried what is on the doc, as you can see in the reproduction repo.

**Comment by peterpeterparker** [comment] 2020-01-23 14:17
In that case please use another channel as it is a support request, thx in advance.

**Comment by Buraky89** [comment] 2020-01-23 14:27
- Exactly what have been instructed in the readme is not working.
- I am not doing anything special. 
- It is reproducable
- When someone with same cordova-ios and xcode (or something) finds this repository, the same will happen only following the instructions on readme. So, the replies will be useful for them.

So what should I do for it to not be a support request? Do all XCode's and all cordova-ios versions have to face this issue, in order for this to be an issue?

**Comment by peterpeterparker** [comment] 2020-01-23 14:33
Which command should I run with your repo to reproduce the problem?

**Comment by Buraky89** [comment] 2020-01-23 14:39
Opening HelloCordova.xcworkspace with XCode 11.1 and trying to build will reproduce the problem

**Comment by peterpeterparker** [comment] 2020-01-23 15:00
Couldn't build neither with XCode.

Still a support request to me regarding Pod and compatibility with iOS@4.5.5.

I reopen the task, you are most welcomed to close it when you'll find the solution and if you could provide afterwards a PR to improve the doc that would be great.

**Comment by peterpeterparker** [comment] 2020-01-23 15:00
Linked with https://github.com/jeduan/cordova-plugin-facebook4/issues/811

**Comment by jvkxhola** [comment] 2020-01-24 17:19
I was having the same problem and maybe i found a way to fix it.

As it was mentioned in #811, the problem was missing Facebook SDKs, which should be specified in PodFile

Switching those lines in the config.xml of this plugin:

```
       <podspec>
            <config>
                <source url="https://github.com/CocoaPods/Specs.git"/>
            </config>
            <pods use-frameworks="true">
                <pod name="FBSDKCoreKit" spec="5.7.0"/>
                <pod name="FBSDKLoginKit" spec="5.7.0"/>
                <pod name="FBSDKShareKit" spec="5.7.0"/>
            </pods>
        </podspec>
```

fot that:
```
        <framework src="FBSDKCoreKit" type="podspec" spec="5.7.0" />
        <framework src="FBSDKLoginKit" type="podspec" spec="5.7.0" />
        <framework src="FBSDKShareKit" type="podspec" spec="5.7.0" />
```

makes the SDKs appear in the PodFile, as it should.

**Comment by simetin** [comment] 2020-02-05 15:52
Hi ! I'm facing the same issue with Cordova iOS 5.1.1. Tried pretty much everything mentioned in the docs and the threads that I found. Anyone know a fix for this version of Cordova ?

**Comment by giuseeFG** [comment] 2020-02-12 16:53
it works using these PODs:

	pod 'FBSDKCoreKit', '~> 5.15.0'
	pod 'FBSDKShareKit', '~> 5.15.0'
	pod 'FBSDKLoginKit', '~> 5.15.0'

and use version="6.3.0" of facebook4 plugin

cheers

**Comment by Senglean** [comment] 2020-02-16 11:13
we are stuck and can't release new update for our game 😭 

cant get past 'FBSDKCoreKit/FBSDKCoreKit.h' file not found

adding the plugin comes with a sudo error (trying to do pods stuff) after which i run various pods commands in platforms/ios ...resolve run paths etc any help will be appreciated

**Comment by Senglean** [comment] 2020-02-16 13:22
Yey i managed to build with xcode 

My problem was coming from the fact I have to use sudo to install the plugin.

**Comment by daveshirman** [comment] 2020-02-24 20:43
I went round in circles on this, only to end up actually reading the readme file [here](https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/ios/README.md):

> If building your project in Xcode, you need to open YourProject.xcworkspace (not YourProject.xcodeproj) so both your Cordova app project and the Pods project will be loaded into Xcode.

So yeah, I did that, then selected the project in the left hand pane and it built as normal.

Hope this helps.

**Comment by tarun57** [comment] 2020-03-04 13:20
I used this code but it can't solve my problem.
Can you please help me more?

**Comment by arielhasidim** [comment] 2020-03-19 10:45
if nothing helps, consider this (i struggled with this for weeks)
[https://github.com/jeduan/cordova-plugin-facebook4/issues/795#issuecomment-568289028](https://github.com/jeduan/cordova-plugin-facebook4/issues/795#issuecomment-568289028)

**Comment by JayzeeHuang** [comment] 2020-03-24 09:05
Have you try ios 5? I used to get this error, but it gone now

**Comment by romonsalve** [comment] 2020-06-18 18:02
In my case update cordova to 9 fix the problem, 
If the pods are installed when you add the plugin, the build will success

**Comment by noahcooper** [comment] 2021-01-27 13:59
This plugin is deprecated. Check out `cordova-plugin-facebook-connect` at https://www.npmjs.com/package/cordova-plugin-facebook-connect. The plugin uses v8 of the Facebook SDK from Cocoapods, and the build succeeds without this error.

**Closed by noahcooper** 2021-01-27 13:59 UTC
