### ISSUE TITLE
iOS - Callback on login for White Label apps

### ISSUE THREAD

**Issue by flastowizka** [jeduan/cordova-plugin-facebook4#767] opened 2019-05-20 18:25 UTC
**Bug or feature request**

[X] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

I have white label apps using the same facebook apps.
com.company.app1
com.company.app2

When i logged in the App1 works fine. But when i try login in the App2 the facebook was opened and the callback login open the App1.

**Expected Behavior**

The callback open the correct app

**Plugin version, OS, devices, etc**

4.2.1

**Comment by peterpeterparker** [comment] 2019-06-07 09:10
I think it's a duplicate of https://github.com/jeduan/cordova-plugin-facebook4/issues/654

It needs a new feature in order to be able to specify a suffix

**Closed by peterpeterparker** 2019-06-07 09:10 UTC
