### ISSUE TITLE
Android release apk build failed with exception: could not find maven dependencies

### ISSUE THREAD

**Issue by ashutoshagg** [jeduan/cordova-plugin-facebook4#310] opened 2016-08-30 07:06 UTC
![screen shot 2016-08-29 at 2 29 27 pm](https://cloud.githubusercontent.com/assets/20081803/18079308/8abbb744-6ead-11e6-9d33-d497962959fa.png)

I am using ionic 2 framework. Up till adding platform everything works fine. When trying to generate apk I get this error. I am running following command to generate apk.
cordova build android --debug.
This was working fine earlier(last successful build was End of July)

**Comment by aaronpcz** [comment] 2016-08-30 11:38
I'm also currently having the same issue.  Any solutions are welcome if anyone has over come these issues.

**Comment by aaronpcz** [comment] 2016-08-30 16:28
Using the Android SDK manager - Installing a bunch of updates got me past this problem and to the next.

Execution failed for task ':processDebugResources'.

> 
com.android.ide.common.internal.LoggedErrorException: Failed to run command:


  Output:

        Failed to generate resource table for split ''

        /Users/XXX/auctionmobile/platforms/android/build/intermediates/res/debug/values-v23/values.xml:6: error: Error: No resource found that matches the given name (at 'cardBackgroundColor' with value '?android:attr/colorBackgroundFloating').

**Comment by fredgalvao** [comment] 2016-08-30 16:32
As you've fixed the initial issue, and is now experiencing a new one, I'll mark this as a duplicate of https://github.com/jeduan/cordova-plugin-facebook4/issues/203 for it's the same as your new issue. Please check that issue for the details, and if the issue persists, comment there with more details.

**Closed by fredgalvao** 2016-08-30 16:32 UTC
