### ISSUE TITLE
How to upgrade facebook GRAPH API version

### ISSUE THREAD

**Issue by karthikrajender** [jeduan/cordova-plugin-facebook4#565] opened 2017-09-19 05:30 UTC
Recently I am getting Message from Facebook to upgrade the GRAPH API to higher version, My current version of GRAPH API is 2.4 now how can i upgrade the API to higher version, whether it is upgraded in the new version of plugin.

**Comment by fredgalvao** [comment] 2017-09-19 06:34
I'll close this as a duplicate of #518.

**Closed by fredgalvao** 2017-09-19 06:34 UTC

**Comment by karthikrajender** [comment] 2017-09-20 15:31
So the answer is this will not be an issue, in case i am creating a new app id in facebook let say the version is 2.11 or 2.10 , will the generated token will work correctly, when i am authenticated in OAuth server

**Comment by fredgalvao** [comment] 2017-09-20 22:02
The answer so far is exactly what was said in [this comment](https://github.com/jeduan/cordova-plugin-facebook4/issues/518#issuecomment-308812393). The important part being:

Open https://developers.facebook.com/tools/api_versioning/, select your app, and ask for migration steps from 2.4 to whatever newest version appear for you (2.4 to 2.10 for me at this moment):
- if you **actually see something in the report**, then we have an issue
- if you **see nothing**, there is nothing to be done
