### ISSUE TITLE
Virus in new version

### ISSUE THREAD

**Issue by jarekskuder** [jeduan/cordova-plugin-facebook4#663] opened 2018-05-24 08:13 UTC
When i updated this plugin to version 2.1.0, Bitdefender finds a virus in app - Adware.Gingermaster.CO. When i uninstall this plugin and reinstall app, no virus detected. Clients are angry about this, can you fix this? There was no problem with older versions of plugin.

**Comment by peterpeterparker** [comment] 2018-05-24 08:30
I have no idea.

Could you plz provide mode details: Which devices? android? Ios? Which versions? You compare which versions of the plugin? Bitdefender version? Installed on the mobile phone? Have you a sample repo? Screenshots? Etc.

Be more specific plz, thx in advance

**Comment by peterpeterparker** [comment] 2018-05-24 08:56
Just tried Bitdefender on my Android 8.1 / Nexus 5X phone with my app installed where I use the last version 2.1.0 of this plugin, results of BitDefender: **NO** virus detected

**Comment by jarekskuder** [comment] 2018-05-24 09:08
Ok, i'm testing on SONY Xperia X Performance (but clients have other phones), Android 8.0.  
Android platform 6.4.0. 
Cordova 7.1.0.
Tried plugin versions 1.10.1, 2.0.0, 2.1.0 - all showed virus detected.
Attaching screenshots when i install app with and without plugin. The menu screenshot shows that i have installed this app (same time).
![33576406_1755342324515243_8398618499320119296_n](https://user-images.githubusercontent.com/14089173/40475821-2db0abaa-5f4b-11e8-8d5c-b312e643f9d4.png)
![33489062_1755329947849814_6839576891637104640_n](https://user-images.githubusercontent.com/14089173/40475822-2dceb622-5f4b-11e8-8ae5-fc3aa97985d7.png)
![33471925_1755342311181911_2754672301441024000_n](https://user-images.githubusercontent.com/14089173/40475823-2deb8e3c-5f4b-11e8-9336-e1123b1d2094.png)

**Comment by peterpeterparker** [comment] 2018-05-24 09:13
@jarekskuder thx for the details

- and with which prior version of the plugin did you not faced the error?

- could you give a try: remove your app, install mine http://play.google.com/store/apps/details?id=io.fluster.fluster and confirm me if you detect the same problem

**Comment by jarekskuder** [comment] 2018-05-24 09:17
@peterpeterparker 
1) Sorry don't know 
2) No detections on your app

**Comment by peterpeterparker** [comment] 2018-05-24 10:30
@jarekskuder thx for the test, this proof that the problem is not linked to this plugin. I tested and you tested my app, which include v2.1.0 of this plugin, on Android with BitDefender which didn't detected any problems.

Furthermore, in the version you enumerated, respectively v1.10.1, v2.0.0 and v2.1.0 nothing changed in terms of Android libs regarding the plugin, still same as previous version.

Unfortunately then, there isn't much I/we can't do here.

Therefore I close the issue. Hope you will find your problem soon!

**Closed by peterpeterparker** 2018-05-24 10:30 UTC

**Comment by peterpeterparker** [comment] 2018-05-24 17:39
Because of the duplicate https://github.com/jeduan/cordova-plugin-facebook4/issues/664 I have created a full dummy app from scratch (ionic start..., installing all libs and this plugin) which, after build (ionic cordova build android --prod), I installed on my phone and tested with BitDefender. Again **NO PROBLEMS** were detected

**Comment by jarekskuder** [comment] 2018-05-25 05:11
@peterpeterparker Ok, maybe you are right at this point, but look, now 2 app's have this problem and i think this is only 2 apps because nobody is checking it with anti-viruses. Maybe if you don't get that problem in your app, that means, the problem not directly in plugin. Maybe when something interacts with the plugin give this problem. But more importantly, it's a simple fact that if the plugin uninstalled, the problem is gone.

**Comment by peterpeterparker** [comment] 2018-05-25 05:21
@jarekskuder I don't get the problem in my productive app and with a fresh blank app. Furthermore there isn't any configuration to tell the plugin to be dependent from this or that libraries, therefore it can't be a problem "not directly linked with the plugin". There aren't any changes in the Android code and dependencies of the plugin since months. 

If you still think there is a problem in the plugin, provide **full details**, a **code repo** or **access to your code** to reproduce the problem
