### ISSUE TITLE
Unable to install cordova-facebook-4 plugin with android 7.0.0

### ISSUE THREAD

**Issue by imromec** [jeduan/cordova-plugin-facebook4#611] opened 2018-01-14 06:42 UTC
> _NEED HELPPPPP!!!
> 
> Failed to install ‘cordova-plugin-facebook4’: Error: ENOENT: no such file or directory, open '/Applications/XAMPP/xamppfiles/htdocs/<app_name>/platforms/android/AndroidManifest.xml’
> at Error (native)
> at Object.fs.openSync (fs.js:640:18)
> at Object.fs.readFileSync (fs.js:508:33)
> at Object.parseElementtreeSync (/Applications/XAMPP/xamppfiles/htdocs/ratnasangh/platforms/android/cordova/node_modules/cordova-common/src/util/xml-helpers.js:180:27)
> at new AndroidManifest (/Applications/XAMPP/xamppfiles/htdocs/ratnasangh/platforms/android/cordova/lib/AndroidManifest.js:29:20)
> at AndroidProject.getPackageName (/Applications/XAMPP/xamppfiles/htdocs/ratnasangh/platforms/android/cordova/lib/AndroidProject.js:99:12)
> at Api.addPlugin (/Applications/XAMPP/xamppfiles/htdocs/<app_name>/platforms/android/cordova/Api.js:223:57)
> at handleInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:594:10)
> at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:357:28
> at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
> (node:7823) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open ‘/Applications/XAMPP/xamppfiles/htdocs/<app_name>/platforms/android/AndroidManifest.xml’_

**Comment by peterpeterparker** [comment] 2018-01-14 07:36
Duplicate of https://github.com/jeduan/cordova-plugin-facebook4/issues/599

**Comment by imromec** [comment] 2018-01-14 07:56
Cordova version: 8.0.0, Ionic version: 3.19.0, Android Version: 7.0.0

**Comment by kevin-lot** [comment] 2018-01-31 11:10
Considerer this pull request #601.
Some paths are changed.

**Comment by peterpeterparker** [comment] 2018-04-21 07:15
This is most probably a conflict with the Android SDK version

See for example #550

For support questions plz use other channels like Stackoverflow or Ionic forum

**Comment by peterpeterparker** [comment] 2018-04-21 07:15
In case of conflict with the Android SDK version, see for example #550

In case of conflict with cordova-android@7 see `Android Guide`

For support questions plz use other channels like Stackoverflow or Ionic forum

**Closed by peterpeterparker** 2018-04-21 07:15 UTC
