### ISSUE TITLE
api method expects 2 arguments instead of 4

### ISSUE THREAD

**Issue by hAz4rd0uS** [jeduan/cordova-plugin-facebook4#684] opened 2018-07-17 12:13 UTC
**Bug or feature request**

[x] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

I installed the cordova plugin facebook4 and ionic-native/facebook, but got an error using the api() method of the plugin, which is documented here.

The plugin is functioning well, but I got a TypeScript error:

Typescript Error Expected 2 arguments, but got 4.

On this line:

` .then((res: FacebookLoginResponse) => this.fb.api(res.authResponse.userID + "/?fields=id,email,first_name&access_token="+res.authResponse.accessToken+"", ["public_profile"],`

According to [this](https://github.com/jeduan/cordova-plugin-facebook4#getting-a-users-birthday) example on your documentation, the api method is taking 4 parameters, eg. the request to the Graph API as well as the fields required, the permission used for the fields, and two success / error callbacks.

Why is the api() call is only waiting for 2 arguments ?

I used the [official example](https://ionicframework.com/docs/native/facebook/) from ionic-native documentation. 

Here's my code:

```
fbLogin(): void {
    var self = this;
    this.fb.login(['public_profile', 'email'])
    .then((res: FacebookLoginResponse) => this.fb.api(res.authResponse.userID + "/?fields=id,email,first_name&access_token="+res.authResponse.accessToken+"", ["public_profile"],
      (result) => {
        let user = new NmUser({
          email: result.email,
          username: result.firstName,
          password: result.id
        });
        self.userService.facebook(user).subscribe(
          (result) => {
            console.log(result);
          },
          (error) => {
            console.log(error);
          }
        );
      }, (error) => {
        console.error("Failed: ", error);
      }
    ))
    .catch(e => console.log('Error logging into Facebook', e));
  }
```

**Expected Behavior**

The api method should take 4 arguments as in my code.

**Plugin version, OS, devices, etc**

cordova-plugin-facebook4 v2.2.0

**Comment by peterpeterparker** [comment] 2018-07-17 12:19
Plz stop creating duplicate issue for your support request (duplicate of yesterday https://github.com/jeduan/cordova-plugin-facebook4/issues/683)

For support plz use other channels. Like I already told you yesterday your mistake is around "function", just don't write them

     this.fb.api('...', ['something']).then((result) => {
             ...
        }, (err) => {
            ...
        });

Plz note: Any other supports requests regarding this from your side will be close without any comments

**Closed by peterpeterparker** 2018-07-17 12:19 UTC

**Comment by peterpeterparker** [comment] 2018-07-17 12:32
you do 

     this.fb.api('...', ['something'], (result) => {}, (err) => {})...

you should (as I displayed above)

     this.fb.api('...', ['something']).then((result) => {...

Note: This was my last msg

**Comment by hAz4rd0uS** [comment] 2018-07-17 12:38
Thanks and sorry for my dumbness...

**Comment by peterpeterparker** [comment] 2018-07-17 12:40
No worries at all

Just plz in the future use other channels for support requests, like the Ionic Forum or Stackoverflow, I would appreciate it

Have fun

**Comment by hAz4rd0uS** [comment] 2018-07-17 12:42
I thought it was an issue since in your doc the api function is taking 4 parameters but maybe this is not the same with ionic-native

**Comment by peterpeterparker** [comment] 2018-07-17 12:45
Typing arrow functions (like in Ionic) != typing vanilla Javascript functions (like in the doc)

https://www.sitepoint.com/es6-arrow-functions-new-fat-concise-syntax-javascript/

**Comment by fredgalvao** [comment] 2018-07-18 01:30
Just to be clear, the issue is not around the differences between fat arrow functions and raw functions in javascript/typescript. The issue is around the fact that you ( @hAz4rd0uS ) were mistaking our docs (which is to be used with the pure js object we emit, and uses a callback-style api) with the ionic native docs (which is to be used with the wrapper that ionic native emits, and uses a promise-style api). Those two objects/APIs are **definitely not the same**, even though one uses the other.
