### ISSUE TITLE
Null Exception Issue with Sharing Dialog on Latest FB Native App (179.0.0.44.83)

### ISSUE THREAD

**Issue by gregavola** [jeduan/cordova-plugin-facebook4#681] opened 2018-07-08 03:32 UTC
**Bug or feature request**

[ X ] I'm reporting a reproducible issue with the code
[ ] I'm reporting a feature request

**Describe the Bug of feature request**

The latest version of Facebook for Android 179.0.0.44.83 which was released on July 6th, 2018 - throws an "null", when trying to invoke the Dialog command.

All sharing attempts on Android return:
`Facebook error: null`

Full stack track:

```
07-07 23:02:23.089 13958-13958/com.XXXX.app W/com.facebook.appevents.AppEventsLogger: deactivateApp events are being logged automatically. There's no need to call deactivateApp, this is safe to remove.
07-07 23:02:23.462 13958-13958/com.XXX.app D/ConnectPlugin: activity result in plugin: requestCode(64207), resultCode(0)
07-07 23:02:23.479 13958-13958/com.XXX.app E/Activity: Error: null
07-07 23:02:23.479 13958-13958/com.XXX.app E/ConnectPlugin: null
```

Sample JS code:

```
const options = {
            method: 'share',
            href: `https://google.com` // any link can be placed here
          };
          this.facebook
            .showDialog(options)
            .then(share => {})
            .catch(err => {
             console.error(err)
           })
```

An `null` is thrown on every attempt to share content. Started happening with the latest release since July 6th.

**Expected Behavior**

Share worked fine with no code changes, prior to the updated Facebook App. Login still works fine as well. If app is not installed sharing works as well.

**Plugin version, OS, devices, etc**

Android (Any version), with Native FB App (179.0.0.44.83)

**Sample repo**

You can test on the latest version of Untappd: https://play.google.com/store/apps/details?id=com.untappdllc.app&hl=en_US

**Comment by peterpeterparker** [comment] 2018-07-08 07:47
@gregavola 

- I could reproduce the problem with my app too

- I spent some times debugging and trying to understand the problem but I couldn't really figure out where it is. Somewhere in the Facebook SDK Android two errors "ApplicationError" and a "null pointer" are just thrown

Therefore I have opened a Facebook bug report because I kind of have the feeling that there isn't much we can't do here, of course except if Facebook provide a release notes and changelog explaining which breaking changes they introduced in their last version

Plz follow and upvote following issue: https://developers.facebook.com/bugs/1789597201131166/

**Comment by nit-agg** [comment] 2018-07-09 12:15
I am also getting this bug in the latest version of facebook app on Android. I am getting an FacebookException "null". The older versions of Facebook app are working fine. Please help.

**Comment by peterpeterparker** [comment] 2018-07-10 17:58
Update (not a winning one) on the Facebook side: they have close the issue I created in order to a possible duplicate reference https://developers.facebook.com/bugs/647119912303459/

**Comment by Slavezax** [comment] 2018-07-12 00:19
Same problem here on Android.

**Comment by peterpeterparker** [comment] 2018-07-12 06:58
There is a new update of the Facebook app available in the Play store v180.0.0.35.82

It's me or it solves the problem?

**Comment by Robot2037** [comment] 2018-07-12 09:52
Yes, ShareDialog works on 180.0.0.35.82.

**Comment by peterpeterparker** [comment] 2018-07-12 09:58
Cool thx for the confirmation. I gonna then close this Facebook-sdk issue

In case it should been reopened, just ping me

**Closed by peterpeterparker** 2018-07-12 09:58 UTC
Labels: facebook-sdk-bug
