### ISSUE TITLE
NullPointerException - UriCodec.decode

### ISSUE THREAD

**Issue by Igor-Puzhai** [jeduan/cordova-plugin-facebook4#675] opened 2018-06-20 08:53 UTC
**Exception java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference**
libcore.net.UriCodec.decode (UriCodec.java:153)
java.net.URLDecoder.decode (URLDecoder.java:60)
org.apache.cordova.facebook.ConnectPlugin.makeGraphCall (ConnectPlugin.java:754)
org.apache.cordova.facebook.ConnectPlugin.access$200 (ConnectPlugin.java:54)
org.apache.cordova.facebook.ConnectPlugin$2$1.onCompleted (ConnectPlugin.java:110)
com.facebook.GraphRequest$1.onCompleted (GraphRequest.java:301)
com.facebook.GraphRequest$5.run (GraphRequest.java:1380)
android.os.Handler.handleCallback (Handler.java:815)
android.os.Handler.dispatchMessage (Handler.java:104)
android.os.Looper.loop (Looper.java:207)
android.app.ActivityThread.main (ActivityThread.java:5857)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1026)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:887)

screenshot: [http://prntscr.com/jx2gdh](url)

this is the first time this crash appeared in this app, facebook login has been working well so far.

**Comment by peterpeterparker** [comment] 2018-06-20 14:15
I close this issue because it doesn't follow the guidelines https://github.com/jeduan/cordova-plugin-facebook4/blob/master/.github/issue_template.md

Furthermore if you would have done at least one search you would have noticed that this is a duplicate of other closed issues like https://github.com/jeduan/cordova-plugin-facebook4/issues/674

**Closed by peterpeterparker** 2018-06-20 14:15 UTC

**Comment by Igor-Puzhai** [comment] 2018-06-20 14:28
thanks for the answer.

but I am using version 2.1.0.

so if 2.0.1 fixed it, how could the crash happen?

**Comment by peterpeterparker** [comment] 2018-06-20 14:34
for support requests plz use other channels

if afterwards you still think it's an issue, plz provide issue correctly formatted with details and repo to reproduce the problem

reference https://github.com/jeduan/cordova-plugin-facebook4/blob/master/.github/issue_template.md

thx in advance
