### ISSUE TITLE
FB.login() called before FB.init().

### ISSUE THREAD

**Issue by JWesorick** [jeduan/cordova-plugin-facebook4#445] opened 2017-02-17 16:53 UTC
Platform: Browser

When I call login I get an error in the console. `FB.login() called before FB.init().` I can probably get around it by directly calling FB.init(), but there doesn't seem to be any documentation on doing this. I'm also using Ionic Native.

```typescript
Facebook.login(FacebookPermissions)
.then(data => {
  console.log(data);
}, err => {
  console.log(err);
});
```

**Comment by dodi-br** [comment] 2017-02-24 12:48
same here, have you solved the problem?

**Comment by JWesorick** [comment] 2017-02-27 16:12
So far it seems like you can just call [FB.init()](https://developers.facebook.com/docs/javascript/reference/FB.init/v2.8) Inside your `app.component.ts` and adding `declare let FB: any;` to the top. I haven't tested everything extensively though. I'm also pretty sure this is a temp workaround and the initialization is supposed to be happing inside the plugin.

**Comment by tictiktak** [comment] 2017-03-19 17:43
@JWesorick: Can you explain the workaround? How can I find `app.component.ts`? Thanks,

**Comment by tictiktak** [comment] 2017-03-20 15:24
It is resolved after I saved  APP_ID, APP_NAME by using --save which I lacked it before.

**Comment by bogomips** [comment] 2017-10-16 11:48
I am trying this plugin for a PWA (so platform browser) and I got the same message.
After some investifations I decided to past my appId inside facebook-browser.js
`
if (window.location.protocol === "file:") {
  console.warn("Facebook JS SDK is not supported when using file:// protocol");
} else {
  window.fbAsyncInit = function() {    
    FB.init({
      appId      : here-I-removed-null-and-added-my-appid, after_prepare hook  // null is populated by the cordova 
      xfbml      : true,
      version    : 'v2.7'
    });

    __fbSdkReady = true;

    for (var i = 0; i < __fbCallbacks.length; i++) {
      __fbCallbacks[i]();
    }
  };
`

It seems to work... can someone explain if it is a bug or a mistake of mine?
thanks

**Comment by mcroker** [comment] 2019-06-17 14:47
For the browser platform, the plugin seems to be using the post prepare plugin to populate the APP_ID.  It assumes this is specified in config.xml in the root of the project. I am not sure why - but this was missing in my config generating the error.

Adding this line to config.xml, seems to resolve the problems

```
    <preference name="APP_ID" value="0123456789"/>
```

Note: the implementation seems to be based on an inline replacement of the special token "APP_ID" in several files (see plugins/cordova-plugin-facebook4/scripts/after_prepare.js).

In my situation this had been set to null (presumably the first time it ran without the above entry in config.xml).  To resolve this I reinstalled the plugin and browser platform.

```
$ ionic cordova plugin remove cordova-plugin-facebook4
$ ionic cordova platform remove browser
$ ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="0123456789" --variable APP_NAME="myApp"
$ ionic cordova platform add browser
```

**Comment by yazan9** [comment] 2019-11-12 07:23
@mcroker : I cannot thank you enough. You are the only one out there who's just totally, nailed it!

**Comment by peterpeterparker** [comment] 2019-11-12 07:27
closing it as it is solved and confirmed by above comments, thx!

**Closed** 2019-11-12 07:27 UTC

**Comment by ramyadavrp** [comment] 2019-11-15 11:20
thanks @mcroker ,
<preference name="APP_ID" value="0123456789"/>
has worked for my ionic 4 app.

**Comment by ibrahimAboelsuod** [comment] 2019-11-29 13:40
@peterpeterparker  This shouldn't be closed yet. The fix is a work around for the real issue.

Cordova now doesn't insert plugins into the `config.xml` and only use the `package.json` file. This plugin was configured to only `config.xml`. It should prioritize `package.json` file as Cordova recommend.

**Comment by mujica93** [comment] 2020-04-02 19:38
> For the browser platform, the plugin seems to be using the post prepare plugin to populate the APP_ID. It assumes this is specified in config.xml in the root of the project. I am not sure why - but this was missing in my config generating the error.
> 
> Adding this line to config.xml, seems to resolve the problems
> 
> ```
>     <preference name="APP_ID" value="0123456789"/>
> ```
> 
> Note: the implementation seems to be based on an inline replacement of the special token "APP_ID" in several files (see plugins/cordova-plugin-facebook4/scripts/after_prepare.js).
> 
> In my situation this had been set to null (presumably the first time it ran without the above entry in config.xml). To resolve this I reinstalled the plugin and browser platform.
> 
> ```
> $ ionic cordova plugin remove cordova-plugin-facebook4
> $ ionic cordova platform remove browser
> $ ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="0123456789" --variable APP_NAME="myApp"
> $ ionic cordova platform add browser
> ```
hello body, a question the APP_ID and the APP_NAME are inside the quotes ?, thanks for your prompt response.

**Comment by ryaa** [comment] 2020-05-09 06:05
Here is a related issue https://github.com/jeduan/cordova-plugin-facebook4/issues/872 and potential fix https://github.com/jeduan/cordova-plugin-facebook4/pull/873

**Comment by gilmonge** [comment] 2020-05-14 19:03
Yeah! Thanks @ryaa 
These changes function perfectly for me.
I promote what this change (#873) should be added at the plugin.

**Comment by kaverlin** [comment] 2020-07-13 16:52
https://github.com/jeduan/cordova-plugin-facebook4/issues/445#issuecomment-502714196
@mcroker it is  simply the best answer !
