### ISSUE TITLE
app crashed in Iphone while using latest version(5.0.0)

### ISSUE THREAD

**Issue by kalaiprakash93** [jeduan/cordova-plugin-facebook4#776] opened 2019-06-29 09:42 UTC
when using 5.0.0 version app is connected to Facebook and then tha main app is closed in iphone6.
while using 4.2.1 it is working fine

**Comment by peterpeterparker** [comment] 2019-06-29 09:45
@kalaiprakash93 I tested the PR of @guylando. #751  with success on an iPhone 6

@guylando any thoughts?

**Comment by peterpeterparker** [comment] 2019-06-29 09:46
also plz provide more details (log, sample app to reproduce the problem etc.)

**Comment by kalaiprakash93** [comment] 2019-06-29 09:53
it is not calling login function,
facebookConnectPlugin.login(['email', 'public_profile'], success, failure)

**Comment by peterpeterparker** [comment] 2019-06-29 09:57
Cordova version? Plugin version? iPhone version= iOS version? real or not real phone? logs? sample app? etc

Plz provide more DETAILS

**Comment by kalaiprakash93** [comment] 2019-06-29 10:01
Real Iphone6,
 ios version:11.0.3,
Plugin Version:5.0.0
 
PhoneGap (iOS / Android / Windows)
cli-8.0.0 (4.5.4 / 7.0.0 / 5.0.0)
Phoeegap online build

**Comment by peterpeterparker** [comment] 2019-06-29 10:10
I just tested again in a brand new clean app with the last version of the plugin and everything went well

### Install

```
ionic start
ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="XXXXX" --variable APP_NAME="XXX"
npm install @ionic-native/facebook --save
```

### Code

```
import {Component} from '@angular/core';

import {Facebook} from '@ionic-native/facebook/ngx';

@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page {

  constructor(private fb: Facebook) {
  }

  openFb() {
    this.fb.login(['public_profile', 'user_friends', 'email'])
        .then((res: any) => alert('Yolo logged into Facebook!'))
        .catch(e => alert('Yolo error logging into Facebook'));
  }

}
```

```
<ion-header>
  <ion-toolbar>
    <ion-title>
      Tab One
    </ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <ion-button (click)="openFb()">Go open Facebook</ion-button>
</ion-content>
```

### Build

```
ionic cordova build ios 
```

> ** ARCHIVE SUCCEEDED **
> 
> Running command: xcodebuild -exportArchive -archivePath MyApp.xcarchive -exportOptionsPlist /Users/...
> ** EXPORT SUCCEEDED **
> 

### Test

Real iPhone 6s / Software version 12.3.1

![IMG_20190629_120848](https://user-images.githubusercontent.com/16886711/60382679-ecb2e700-9a66-11e9-8620-a751b76eacbc.jpg)

**Comment by kalaiprakash93** [comment] 2019-06-29 10:12
I am using build.phonegap.com

**Comment by peterpeterparker** [comment] 2019-06-29 10:13
Could you give a try with an iOS v12?

**Comment by peterpeterparker** [comment] 2019-06-29 10:14
And one more time, provide LOGS, SAMPLE APP and MORE DETAILS

**Comment by kalaiprakash93** [comment] 2019-06-29 10:35
i will check and let you know.
and one more issue, sometimes in android "CONNECTION_FAILURE" error is coming while login

**Comment by peterpeterparker** [comment] 2019-06-29 10:37
I tested successfully on Android too. Same provide LOGS, SAMPLE APP and MORE DETAILS in case you notice a problem, thx in advance

**Comment by peterpeterparker** [comment] 2019-06-29 10:38
Also keep @guylando in the loop as author of the only PR merged in last release

**Comment by guylando** [comment] 2019-06-29 19:08
I see the following crashes in production on Iphone 6s, Iphone xs, Iphone xs max:
![image](https://user-images.githubusercontent.com/14879163/60388456-74761100-9aba-11e9-8abb-f7e6f0b45756.png)

**Comment by peterpeterparker** [comment] 2019-06-29 19:13
So what's the plan? That's a FB SDK problem? Should we rollback your PR?

**Comment by guylando** [comment] 2019-06-29 19:23
My company is not going to go back to the outdated plugin/SDK. This requires investigation/solution. From a look at the stack trace it seems like simply an invalid argument situation.
I hope I am not the only one who can read the code and solve this. At this time I dont have time to deal with this. I don't think it is only "my problem".

**Comment by peterpeterparker** [comment] 2019-06-29 19:32
As the plugin update was requested many times (#750, #751 and #770) and as FB is asking for an update of the SDK I'm also guessing that most people rather like to have the ability to upgrade aka to not downgrade/rollback

About the problem itself then, if anyone find a solution and could provide a PR, ping me, I'll be happy to merge it

**Comment by bandodebits** [comment] 2019-07-03 17:35
Crash on iPhone 8 Plus, IOS 12.3.1, Facebook SDK 5.0.2
+[FBSDKBasicUtility objectForJSONString:error:]: unrecognized selector sent to class 0x1030c8908

**Comment by guylando** [comment] 2019-07-03 18:19
Anyway have steps to reproduce?
Maybe this can help: https://stackoverflow.com/questions/53112248/unrecognized-selector-sent-to-class-coming-from-facebook-sdk

**Comment by ldiaz** [comment] 2019-07-10 15:35
> Anyone has steps to reproduce?
> Maybe this can help: https://stackoverflow.com/questions/53112248/unrecognized-selector-sent-to-class-coming-from-facebook-sdk
> [facebook/facebook-sdk-for-unity#208 (comment)](https://github.com/facebook/facebook-sdk-for-unity/issues/208#issuecomment-492118442)
> [facebook/facebook-sdk-for-unity#208 (comment)](https://github.com/facebook/facebook-sdk-for-unity/issues/208#issuecomment-456600098)
> Seems the solution is to compile/link with -force_load flag, can anyone confirm? if so then this bug is not related to the plugin

@guylando  I tried many related and supposed "fixes" from past similar error message, included that flag and no luck. On issue #780  I mentioned created a blank app that reproduces the error in case you can look on that. Its here  https://github.com/ldiaz/cordova-plugin-facebook4/tree/master.   (Ionic - capacitor - with only facebook plugin installed and configured)

**Comment by peterpeterparker** [comment] 2019-07-11 05:06
There are newer version of the Facebook iOS SDK (this plugin is currently using v5.0.2 and the most recent one is currently v5.2.1). Maybe updating it would solve the issue?

Therefore, as no one is able to provide a way to reproduce the issue, could someone who's facing the issue, try to pull out the plugin, update the Fb iOS SDK to most recent and try it in his/her app to check if that solve the issue?

**Comment by jcesarmobile** [comment] 2019-07-23 15:43
For people facing the `+[FBSDKBasicUtility objectForJSONString:error:]: unrecognized selector sent to class` in Capacitor apps, you have to add -ObjC flag because it's required by Facebook's SDK, but on Cordova it's a default flag, so it's not needed there.

You can see an example of how to add the flag here:
https://github.com/ldiaz/cordova-plugin-facebook4/pull/1

**Comment by andreas-aeschlimann** [comment] 2019-07-23 21:44
I can confirm the same issue with cordova-plugin-facebook4 v5.0 in my Ionic Angular v4.0 project with Capacitor. Downgrading to cordova-plugin-facebook4 v4.2.1 "fixed" the issue for me.

I have not tried the suggestion of @jcesarmobile yet. I will report back later.

**Comment by mcherubin** [comment] 2019-07-26 15:55
Has anyone solved this issue?

**Comment by thehuangkai** [comment] 2019-08-05 09:37
Similar issue here,
I am using:

Ionic 3.9.2
cordova-plugin-facebook4: 5.0.0
facebook sdk for iOS: 5.0.2

iOS cannot login.

**Comment by voltairebiton** [comment] 2019-08-15 13:39
i m using capacitor and @jcesarmobile 's answer worked

**Comment by peterpeterparker** [comment] 2019-08-19 20:12
I just released a new version of the plugin (v6.0.0) which, furthermore than introducing Cocoapods for the iOS dependencies, also bump the Facebook SDK version to v5.2.x

Could someone who's facing the above problem try to update his/her app and tell the other if he/she still face the error or not?

The Facebook SDK release notes (https://github.com/facebook/facebook-objc-sdk/blob/master/CHANGELOG.md) is vague but mention many times "Various bug fixes"

**Comment by andreas-aeschlimann** [comment] 2019-09-08 20:19
I had the latest v5.x and this crash appeared within my Ionic v4 app. After updating this plugin to v6.x, the crash was not appearing anymore.

**Comment by peterpeterparker** [comment] 2019-09-08 20:39
@andreas-aeschlimann cool thx for the feedback! therefore I think we could close this issue

if anyone is facing the error with the most recent Facebook SDK, of course ping and provide details

**Closed by peterpeterparker** 2019-09-08 20:39 UTC

**Comment by omereGlobalbit** [comment] 2019-11-18 15:59
still happening 5.11.0
