### ISSUE TITLE
minSdkVersion 15

### ISSUE THREAD

**Issue by xale76** [jeduan/cordova-plugin-facebook4#661] opened 2018-05-22 10:37 UTC
hello, as You may know, from August Android Store will accept minSdk set to 26.
In my PhoneGap build I set minSdk to 26 and I got this error coming from Facebook Plugin

uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [org.xwalk:xwalk_core_library:22.52.561.4] /build/intermediates/exploded-aar/org.xwalk/xwalk_core_library/22.52.561.4/AndroidManifest.xml

What's the solution?

**Comment by peterpeterparker** [comment] 2018-05-22 13:14
Thx for the issue, gonna have a look later

Side note: Api 26 in August mandatory for new app which will be newly submitted. App updates will have till November to upgrade to Api 26

**Comment by peterpeterparker** [comment] 2018-05-22 14:31
I just tried and didn't faced any errors. In my `config.xml` I have set

    <preference name="android-minSdkVersion" value="26" />
    <preference name="android-targetSdkVersion" value="26" />

and was able to build successfully my app.

Looking again to your error msg it seems that the problem doesn't comes from the plugin but rather from Crosswalk which is deprecated.

Furthermore the error msg you are facing doesn't say something about Api 26 but rather something about Api 15 and 16 (not 26). This plugin set the min sdk to 15 and crosswalk to 16, I think that's your problem.

Try to remove your crosswalk plugin to see if that solve your issue. If you can't or won't remove crosswalk, feel free to fork this plugin and set the min-sdk version to the number you want.

Therefore I close this issue.

P.S.: Anyhow, at some point it will be good to set Api 26 instead of 15 in the `plugin.xml` of this plugin (even if that will not make a bug difference). About this I opened the following feature request https://github.com/jeduan/cordova-plugin-facebook4/issues/662

**Closed by peterpeterparker** 2018-05-22 14:31 UTC

**Comment by peterpeterparker** [comment] 2018-05-22 15:38
@xale76 I copy here your question about SDK_VERSION since it's not related to the issue you commented:

> I forked and changed minsdkversion to 26 (from 15)
> The build fails. maybe because of ANDROID_SDK_VERSION set to 4+?
> what I have to set there?

So, to solve this you could have a look at following issue https://github.com/jeduan/cordova-plugin-facebook4/issues/650

But the most easy solution is to not use an outdated cordova-android version

If you have to stick to an old version of cordova-android you could try one of the solution described in https://github.com/jeduan/cordova-plugin-facebook4/issues/650 but since you fork the plugin you could also remove everything related to ANDROID_SDK_VERSION in your fork and you may be good

**Comment by peterpeterparker** [comment] 2018-05-22 15:44
@xale76 yep you are right

again

A. upgrade your cordova-android

but

B. if you can't

1. you could edit manually your local platform gradle / project.properties and add the library, something like
2. you could try to edit your fork respectively edit the `plugin.xml` file of your fork of this plugin and remove anything related to `ANDROID_SDK_VERSION` and reinstall your fork in your app

or if nothing work, feel free to submit a PR to the plugin a solution you found better

**Comment by xale76** [comment] 2018-05-22 16:22
Thank you for helping me. this is my first time that I fork :(
I compile with phonegap CLI 7.1.0

The problem I found is this one

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithJarMergingForRelease'.
> com.android.build.api.transform.TransformException:
java.util.zip.ZipException: duplicate entry:
com/google/zxing/aztec/AztecDetectorResult.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.

BUILD FAILED


-----------------------------------------------

I would like to inform you that without facebook-plugin (my fork or the
original one) the build success.


2018-05-22 17:44 GMT+02:00 David Dal Busco <notifications@github.com>:

**Comment by xale76** [comment] 2018-05-22 16:27
please don't abandon me.:(
If i compile with minsdkversion 15 on my config.xml with facebook plugin
the build success
If i compile with minsdkversion 26 on my config.xml with facebook plugin
the build fails
If i compile with minsdkversion 26 on my config.xml WITHOUT facebook plugin
the build success.

How can you say that the problem is not the plugin?


2018-05-22 18:25 GMT+02:00 David Dal Busco <notifications@github.com>:

**Comment by peterpeterparker** [comment] 2018-05-22 16:33
I can't reproduce the error

     ionic start mytestproj
     cd mytestproj
     npm install
     ionic cordova platform add android@latest
     vim config.xml
     add manually min SDK 26
     ionic cordova plugin add facebook4 etc.
     ionic cordova build android

=> NO ERROR

This is my last msg about this, sorry, took already much time to try to help and bring ideas

**Comment by GuiCarneiro** [comment] 2018-05-27 03:44
I did all of the same steps and still isn't working 

![captura de tela 2018-05-27 as 00 43 31](https://user-images.githubusercontent.com/5458742/40582274-0a8c7e80-6147-11e8-9201-a7b092b5dcf8.png)
