### ISSUE TITLE
No native login dialog iOS

### ISSUE THREAD

**Issue by nikolaz111** [jeduan/cordova-plugin-facebook4#114] opened 2016-01-21 23:22 UTC
I put my bundle id and activated deep linking in the facebook dashboard in order to have a native dialog for facebook login but still no native dialog for iOS (iOS9). Any help appreciated.

**Comment by jeduan** [comment] 2016-01-22 01:27
Duplicate of a lot of other issues.

**Closed by jeduan** 2016-01-22 01:27 UTC
