### ISSUE TITLE
Share Dialog empty

### ISSUE THREAD

**Issue by BenitoP** [jeduan/cordova-plugin-facebook4#36] opened 2015-09-09 21:07 UTC
So I am using the following code as per the readme but the dialog is completely empty with no image or any of the text. I did complete the share and entered my own text, which worked, but pointless. The sharing works fine when the native Facebook app is not installed on the device. 

```
facebookConnectPlugin.showDialog({
    method: "share",
    picture:'https://www.google.co.jp/logos/doodles/2014/doodle-4-google-2014-japan-winner-5109465267306496.2-hp.png',
    name:'Test Post',
    message:'First photo post',
    caption: 'Testing using phonegap plugin',
    description: 'Posting photo using phonegap facebook plugin'
  }, function (response) {
    console.log(response)
  }, function (response) {
    console.log(response)
  }
);
```

Cordova version 5.2.0
Cordova Android version 4.1.1

Any help would be greatly appreciated.

**Comment by jeduan** [comment] 2015-09-09 22:42
Please use the feed method. Facebook stopped supporting the share method on their latest SDK. This is fixed on the next version.

**Comment by BenitoP** [comment] 2015-09-10 06:48
Changed it from "share" to "feed". Now I am getting this in Logcat: "The publish_actions permissions are missing, the share will fail unless this app was authorized to publish in another installation." and only get an instant "Ok" response

**Comment by taejaehan** [comment] 2015-10-29 07:57
Change the 'href' as 'link' in buildContent function in the file ConnectPlugin.java.
it works for me :)

**Comment by santimaya** [comment] 2015-11-03 03:40
Same issue here, i've changed from share to feed and nothing gets shared. Using Cordova iOS 3.9.2.

facebookConnectPlugin.showDialog({
    method: "feed",
    picture:'https://www.google.co.jp/logos/doodles/2014/doodle-4-google-2014-japan-winner-5109465267306496.2-hp.png',
    name:'Test Post',
    message:'First photo post',
    caption: 'Testing using phonegap plugin',
    description: 'Posting photo using phonegap facebook plugin'
  }, function (response) {
    console.log(response)
  }, function (response) {
    console.log(response)
  }
);

Any help would be appreciated.

**Comment by santimaya** [comment] 2015-11-03 04:01
It works on simulator but not on device

<img width="374" alt="captura de pantalla 2015-11-03 a las 0 58 27" src="https://cloud.githubusercontent.com/assets/14928131/10901020/55ee40ce-81c6-11e5-88ea-6320015e35d7.png">
![img_2442](https://cloud.githubusercontent.com/assets/14928131/10901021/55f1de0a-81c6-11e5-99a1-a19d908d9812.png)

**Comment by BenitoP** [comment] 2015-11-03 06:27
The fix for me was simply to upgrade my Cordova and Android to the latest versions ( Cordova - 5.2.0 & Android 3.6.4). After upgrading there were no more issues with the plugin.

**Comment by santimaya** [comment] 2015-11-03 12:46
I'm Running:

Cordova 5.3.3
Cordova iOS 3.9.2

Still not working.

**Comment by auching** [comment] 2015-11-12 02:33
it's still not working, after two months

**Comment by renanvs** [comment] 2015-12-18 19:08
Still empty on device, simulator works fine

**Comment by MTShare** [comment] 2016-02-12 09:22
+1

**Comment by edriang** [comment] 2016-02-15 21:37
I could correct the behaviour by modifying FacebookConnectPlugin.m, adding after line 270 the following:
    ```
dialog.mode = FBSDKShareDialogModeNative; // if you don't set this before canShow call, canShow would always return YES
        if (![dialog canShow]) {
            // fallback presentation when there is no FB app
            dialog.mode = FBSDKShareDialogModeFeedBrowser;
        }

```
I followed this solution from SO: http://stackoverflow.com/a/33152056/1738363

It's now sharing description and picture as expected

**Comment by jeduan** [comment] 2016-02-15 23:05
@edriang can you send a PR?

**Comment by Hirbod** [comment] 2016-04-23 16:11
@edriang could you please send a PR using the current codebase? Thanks!

**Comment by Heshyo** [comment] 2016-05-17 01:53
Like @edriang said, you can force the plugin to not use the app and use the browser instead when sharing, but it sounds more like a hack than a real solution. Also it looks like there's been a new commit since his suggested code: https://github.com/jeduan/cordova-plugin-facebook4/pull/207/commits/0078d0977afd83addda4ce5630a3627b447142ec

As a temporary fix, I always do `dialog.mode = FBSDKShareDialogModeFeedBrowser;` no matter what.

**Comment by allurco** [comment] 2016-05-17 19:17
Having issues as well with the shareDialog:

`Error in Success callbackId: FacebookConnectPlugin1718861795 : TypeError: Cannot read property 'post_id' of null`

Cordova 6.1.1
cordova-android@5.1.1

Not sure what is going on...

**Comment by allurco** [comment] 2016-05-17 19:30
Alright! Changing link to href, adds the link/href and changes the share dialog. I still have he post_id issue.

**Comment by Heshyo** [comment] 2016-05-18 01:25
@allurco: Do you have the Facebook app installed? If yes can you try uninstalling it first and then try sharing again?

**Comment by robertarnesson** [comment] 2016-06-13 21:05
https://github.com/jeduan/cordova-plugin-facebook4/commit/895fffad2064d794e3fa60ea60c71d2c369b4376

**Closed by robertarnesson** 2016-06-13 21:05 UTC

**Comment by neilmctee** [comment] 2017-01-29 19:45
I'm seeing the same problem as the OP (feed dialog **without a link**) results in the dialog opening, but is completely empty.

As the OP's problem appeared to be solved by updating Cordova / Android versions (and I'm way past those recommended versions) is there a chance this has been caused by a regression?

I'm building a Meteor / Android app.... Cordova 6, Android 6.0.
