### ISSUE TITLE
native facebook share dialog is blank in ios9

### ISSUE THREAD

**Issue by jjrchrds** [jeduan/cordova-plugin-facebook4#206] opened 2016-04-27 17:56 UTC
When logged into the Facebook app on ios, if I use the showDialog method share, the parameters except href are being ignored.

When logged out of the Facebook app on ios, the share dialog is loaded in the browser, and all content displays and shares correctly.

On Android this works expected, whether I am signed into Facebook or not.

**Comment by DavidSunny** [comment] 2016-04-28 08:32
+1

**Comment by spmvanmierlo** [comment] 2016-05-03 09:10
Having the same problem!

**Comment by Heshyo** [comment] 2016-05-17 01:48
I'm getting the same on iOS only if the FB app is installed. If FB is not installed then it's working fine. Like @spmvanmierlo said, it's a duplicate of https://github.com/jeduan/cordova-plugin-facebook4/issues/36

On Android it's working fine on several devices whether the FB app is installed or not. I do get an error on one Android (which is in version 5.x while others are in version 4.x, but I don't know if it's linked).
![android_error](https://cloud.githubusercontent.com/assets/6860101/15308891/6535474c-1c14-11e6-8177-9bbcaa73728d.png)

**Comment by peterpeterparker** [comment] 2018-06-23 07:43
Close, inactivity since 2016

**Closed by peterpeterparker** 2018-06-23 07:43 UTC
