### ISSUE TITLE
Facebook Graph API v 2.4

### ISSUE THREAD

**Issue by karthikrajender** [jeduan/cordova-plugin-facebook4#536] opened 2017-07-22 04:57 UTC
I got message from Facebook about the usage of GRAPH API v2.3 and wants to upgrade to GRAPH API v2.4, is there any fix available for this issue ?

**Comment by fredgalvao** [comment] 2017-07-22 05:47
I'll close this as a duplicate of https://github.com/jeduan/cordova-plugin-facebook4/issues/518. Please read the comments there, and if that's not your case, feel free to reopen this and provide more details.

**Closed by fredgalvao** 2017-07-22 05:47 UTC

**Comment by karthikrajender** [comment] 2017-09-23 05:08
Hi fredgalvao

Open https://developers.facebook.com/tools/api_versioning/, select your app, and ask for migration steps from 2.4 to whatever newest version appear for you (2.4 to 2.10 for me at this moment):

i have checked in this link with my app , it shows the following message:

Your app hasn't made enough calls to the Graph API to show any info for the methods you selected between v2.4 and v2.10. Visit our changelog to see the full list of changes in all versions.

based on this whether i need to upgrade or not ?

**Comment by fredgalvao** [comment] 2017-09-23 09:07
I have already answered you that question [on this comment](https://github.com/jeduan/cordova-plugin-facebook4/issues/565).
