### ISSUE TITLE
Plugin returns 'connected' after removing permissions.

### ISSUE THREAD

**Issue by soshman** [jeduan/cordova-plugin-facebook4#693] opened 2018-08-21 08:28 UTC
Hey, thanks for your great work on the plugin.

I've encountered unexpected behaviour after deleting permission for my Facebook app.
Plugin keeps returning status 'connected' on login attempt. When I try to login on our website I get 'not_authorized' status from Facebook SDK.
I managed however achieve option to reconfirm application once. It seemed kinda cached somehow - situation happened a few hours after removing permissions. I could not reproduce this situation.

I use plugin version 2.2.0.
Device I test app on is iPhone 5S with iOS version 11.4.1.

**Comment by peterpeterparker** [comment] 2018-08-21 15:11
> I could not reproduce this situation.

Not that much info, you could not reproduce the problem, you couldn't provide and find a clear flow of the error and what happened on the device, no repo to reproduce the error etc. to speak frankly, for these reasons, I think there is almost no chance we could do something here

Therefor I close the issue

But feel free to ping me if you could provide more  detailed and more information, a reproducible flow and maybe even a repo, thx in advance

**Closed by peterpeterparker** 2018-08-21 15:11 UTC
