### ISSUE TITLE
Crash After Login second time

### ISSUE THREAD

**Issue by cafeasia3** [jeduan/cordova-plugin-facebook4#568] opened 2017-09-26 07:25 UTC
I am using ionic v1, when user login first time its fine, the facebook doesnt ask email and pass it shows popup then its logged in, then I logout using 
```
facebookConnectPlugin.logout(function(){
	          $ionicLoading.hide();
	        });
```
then when I login again, this time the popup asked email and password, then my ionic app is crashed after log in. `facebookConnectPlugin.getLoginStatus(function(response)` this status return **unknown**

any idea whats wrong?

**Comment by wizajay** [comment] 2017-09-27 18:16
Yeah there is some bug there. And in your code, add the error call back to what it returns. 

    facebookConnectPlugin.logout(function(data){
        alert(JSON.stringify(data));
    },function(error){
        alert(JSON.stringify(error));
    });

**Comment by cafeasia3** [comment] 2017-09-30 09:19
yes, it returned OK, but the second login crash the ionic app.

any work around this? or just dont need to logout the facebook?

**Comment by andevit** [comment] 2018-02-22 17:54
Has anyone managed to solve this problem?

**Comment by masoodusmani** [comment] 2018-04-05 10:41
@andevit Hi, my PR fixes the crash. I haven't seen any side effects so far, but I'd appreciate @jeduan or someone else checking it.

**Comment by peterpeterparker** [comment] 2018-04-07 10:04
if the `getLoginStatus` return `unknown` you have to login again before doing anything

     this.facebook.getLoginStatus().then((success) => {
            if (success.status === 'connected') {
                 // cool
            } else {
                this.facebook.login(['public_profile']).then((response) => {
                     // cool
                }, (error) => {
                     // damn
                });
            }
        }, (error) => {
              // damn
        });

could you give a try @cafeasia3 ?

**Comment by A110SHT** [comment] 2018-04-25 06:51
@peterpeterparker  it's still crash. Can not login again with Facebook after logout. when i try to login second time it return "undefined" and try to login again it crash. Any solution.

**Comment by peterpeterparker** [comment] 2018-04-25 06:59
@A110SHT 

there is a lack of details in your question, sorry but I can't give an answer based on "it crash". which os? which os version? which version of the plugin? and important how does your code looks like? could you provide a sample repo? what's the stacktrace? etc.

you could try your luck with the PR #642 if you wish (note:  I personally don't plan to merge it, maybe other maintainers will)

**Comment by peterpeterparker** [comment] 2018-04-25 10:14
@A110SHT spontaneously I would say that the first error is in your code, `getLoginStatus` return a promise (see my above code example). But to me it then looks like a support inquiry, so plz use channels like Stackoverflow or Ionic forum to solve your issue, thx in advance

**Comment by peterpeterparker** [comment] 2018-04-28 08:47
Finally @JoaquinR submitted a sample repo on the Ionic Forum (https://forum.ionicframework.com/t/unable-to-install-cordova-facebook-4-plugin-with-android-7-0-0/118170/8) and therefore I was able to reproduce the problem of app crashing after a second login on Android

I solved the issue with following commit https://github.com/jeduan/cordova-plugin-facebook4/commit/b594d3259af766a00fbc98304d31101044e3bb50

This patch v2.0.1 is now released and available in npm, therefore I close this issue

**Closed by peterpeterparker** 2018-04-28 08:47 UTC

**Comment by Ashis27** [comment] 2018-06-21 07:18
After a long time, finally got a superb solution.
Thanks @**peterpeterparker** for your help.

Please check if you have not done yet the following process
---------------------------------------------------------------------
1. cordova plugin rm cordova-plugin-facebook4
2. npm uninstall cordova-plugin-facebook4
3. cordova plugin add cordova-plugin-facebook4@2.1.0 --save --variable APP_ID="*********" --variable APP_NAME="your app name"
4. npm install cordova-plugin-facebook4
5. cordova platform rm android
6. cordova platform add android (7.0.0)

It's working fine now. Please try.

**Comment by JianhuisHuang** [comment] 2019-10-31 10:21
> if the `getLoginStatus` return `unknown` you have to login again before doing anything
> 
> ```
>  this.facebook.getLoginStatus().then((success) => {
>         if (success.status === 'connected') {
>              // cool
>         } else {
>             this.facebook.login(['public_profile']).then((response) => {
>                  // cool
>             }, (error) => {
>                  // damn
>             });
>         }
>     }, (error) => {
>           // damn
>     });
> ```
> 
> could you give a try @cafeasia3 ?

I have try with plugin version 5.0.0 and on ionic4, iOS 12, but not work. It still login as the same account @peterpeterparker , thanks.
