### ISSUE TITLE
App won't open in iOS

### ISSUE THREAD

**Issue by kloppster** [jeduan/cordova-plugin-facebook4#52] opened 2015-09-25 16:00 UTC
Everything appears to be setup fine, and the Deep Linking is set to Yes, however whenever I run the login() method it still brings up the web browser. Any ideas?

**Comment by jeduan** [comment] 2015-09-25 16:40
This is a duplicate of a few open issues in this repo and the way the Facebook SDK is programmed for in iOS 9.

**Closed by jeduan** 2015-09-25 16:40 UTC
