### ISSUE TITLE
getting error code 4201- "user cancelled dialog

### ISSUE THREAD

**Issue by icernn03** [jeduan/cordova-plugin-facebook4#259] opened 2016-07-09 07:52 UTC
I am getting error "4201-user cancelled dialog" before login page is loaded. login page does load even after the error but does nothing even if login button is clicked. Login data and token received after authentication is sent to my server to authenticate my api for the application
Can I directly send facebook auth response to my server and receive authentication from my api too
```
facebookConnectPlugin.login(["public_profile","user_birthday"],function(result){
    console.log(result);
    facebookConnectPlugin.api(result.authResponse.userID+"/?fields=id,name,picture,birthday",['user_birthday'],
      function onSuccess (userData) {
        console.log("Result: ", userData);

        var credentials = {
          'provider' :'facebook',
          'uid' : result.authResponse.userID,
          'accessToken' : result.authResponse.accessToken,
          'name' : userData.name,
          'picture' : userData.picture.data.url,
          'birthday' : userData.birthday
        };
        $http.post(configs.domain+'/register',{'credentials':credentials}).then(function(response){
          console.log(response);
        });
      },function onError (error) {
        console.error("Failed: ", error);
      } 
    );
    },function(error){
      console.log(error);
    });
```

**Comment by oliviertassinari** [comment] 2016-07-09 10:25
Duplicate of https://github.com/jeduan/cordova-plugin-facebook4/issues/125?

**Comment by robertarnesson** [comment] 2016-07-11 18:48
see #125 and my 2 cents are run facebookConnectPlugin.getLoginStatus first to see if user is already logged in, and only if not you run facebookConnectPlugin.login

**Closed by robertarnesson** 2016-07-11 18:48 UTC
