### ISSUE TITLE
Ionic build - missing ANDROID_SDK_VERSION

### ISSUE THREAD

**Issue by dhavalsoni2001** [jeduan/cordova-plugin-facebook4#650] opened 2018-04-24 10:19 UTC
`ionic build android` throwing an error and not able to generate APK.

![screen shot 2018-04-24 at 3 46 45 pm](https://user-images.githubusercontent.com/11704436/39181274-cc305ec4-47d6-11e8-93ff-bd038b376465.png)

System information:

Cordova CLI: 6.5.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 1.3.2
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.9.2 
ios-sim version: Not installed
OS: Mac OS X El Capitan
Node Version: v6.11.4
Xcode version: Xcode 9.2 Build version 9C40b

**Comment by dhavalsoni2001** [comment] 2018-04-24 10:45
@peterpeterparker  
config.xml  : 
```
  <plugin name="cordova-plugin-facebook4" spec="git+https://github.com/jeduan/cordova-plugin-facebook4.git">
    <variable name="APP_ID" value="FB_APP_ID"/>
    <variable name="APP_NAME" value="FB_APP_NAME"/>
  </plugin>
```

**Comment by peterpeterparker** [comment] 2018-04-24 10:49
could you check if the following piece of code does exist in your `plugins/cordova-plugin-facebook4/plugin.xml` ?

    <preference name="ANDROID_SDK_VERSION" default="4.+"/>

**Comment by dhavalsoni2001** [comment] 2018-04-24 10:53
Yes its there.

**Comment by skaman** [comment] 2018-04-24 10:56
@dhavalsoni2001 did you updated the plugin or just installed it?

**Comment by dhavalsoni2001** [comment] 2018-04-24 11:00
I have tried with update its not working so I have uninstall it and then install it, still its not working.

**Comment by peterpeterparker** [comment] 2018-04-24 11:03
I guess if you add following variable it should works but shouldn't the default value be picked @skaman  ?

    <variable name="ANDROID_SDK_VERSION" value="4.+"/>

**Comment by skaman** [comment] 2018-04-24 11:12
@dhavalsoni2001 you can try to add the variable inside the config.xml as @peterpeterparker said, but i've some doubts because ionic have also the same values in packages.json and maybe also in other places.

I think your cordova version is not handling correctly the default variable. My ideas are:
- update your cordova cli that maybe is too old. I'm using cordova 7.1.0 (after cordova update you maybe need to remove and readd the plugin)
- try to specify the sdk version when you install it. Ex: ionic cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication" --variable ANDROID_SDK_VERSION="4.+"

**Comment by peterpeterparker** [comment] 2018-04-24 11:16
@dhavalsoni2001 if you upgrade to cordova-android@7 have a look to the Android Guide  to configure correctly the plugin https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/android/README.md

@skaman could you give a try with a dummy repo to double check that the `ANDROID_SDK_VERSION`  correctly get a default value even if not defined in `config.xml`, just to be sure?

**Comment by skaman** [comment] 2018-04-24 11:29
@peterpeterparker i was speaking about cordova cli version, the cordova android version could stay the same.

I did a test creating a ionic project from scratch and adding the plugin. The default variable is not saved inside the config.xml but is used correctly from the platform (you can find it inside the file platforms/android/android.json). The project compile succesfully.

I attach the shell log about my test
[facebook-plugin-ionic-test.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/1942500/facebook-plugin-ionic-test.txt)

**Comment by peterpeterparker** [comment] 2018-04-24 11:37
@skaman thx for pointing that out and THX A LOT for double checking!

this confirm that there isn't any problem not having the variable `ANDROID_SDK_VERSION` in config.xml even with `cordova-android` < 7

we could keep the issue open for a bit till op fix his/her problem in his/her project  but it looks like not related to the code of the plugin itself

**Comment by tmzblue** [comment] 2018-04-25 16:37
Hello guys,

I'm also getting the same error in my Ionic project.

Initially, I thought it could be some sort of misconfiguration. To sort things out, I created a new Ionic starter project, installed the plugin and tried to build the .apk. Unfortunately, the build failed. 

I'm attaching the log with the commands I used to repro the problem:
[starter-project-console-log.txt](https://github.com/jeduan/cordova-plugin-facebook4/files/1947937/starter-project-console-log.txt)

Any help appreciated.

System Info:
Cordova CLI: 6.5.0
Ionic CLI Version: 1.7.16
OS: Windows 10 Pro

**Comment by peterpeterparker** [comment] 2018-04-25 18:11
First of all thx @tmzblue I really appreciate your detailed feedback!

So it looks like the problem is what @skaman described above, you also use an older version of the cordova cli

Therefore I see the following solutions:

1. @skaman do you think you could improve the code in order to be compatible with older cordova version?

2. if no, should we "just" add a notice in the "android guide" of the plugin in order to make it clear that in case of cordova cli <7 the property `ANDROID_SDK_VERSION` as to be specified in the config.xml

or 

3. do we rollback the PR

let me know guys what you think/rather like. I'm fine with adding a notice in the guide but I'm open

**Comment by peterpeterparker** [comment] 2018-04-26 06:07
I have added a notice about the compatibility with older Cordova CLI in the Android Guide https://github.com/jeduan/cordova-plugin-facebook4/blob/master/docs/android/README.md

Summarized:

- Android CLI <7, `ANDROID_SDK_VERSION` has to be specified in `config.xml` or at install time in order to set the default value "4.+" because otherwise it won't found. You could also update your old Cordova CLI if you could and that will solve the issue too

- Android CLI >= 7, no problem

Therefore I close the issue.

In case you would be not agree with this, no problemo, let me know. I just think that the CLI 6.5 is relatively old and therefore that this is acceptable.

**Closed by peterpeterparker** 2018-04-26 06:07 UTC

**Comment by skaman** [comment] 2018-04-26 12:03
@peterpeterparker yes, in my opinion update the doc is the better solution (but i needed that fix, so my opinion is based on my needs 😁).

I don't think there is any workaround to avoid the issue by code.

@dhavalsoni2001 and @tmzblue have you tried to update the cli or specify manually that variable? Is it working?

**Comment by tmzblue** [comment] 2018-04-26 12:52
Hello @peterpeterparker and @skaman,

I agree with the solution. After updating cordova cli to v8 I ran some tests and the problem was gone.

Thx! :stuck_out_tongue:

**Comment by peterpeterparker** [comment] 2018-04-26 12:53
@skaman @tmzblue cool thx for testing and for your feedbacks!

**Comment by giangambero** [comment] 2018-04-30 21:32
Hello, i'm getting the same error with cordova cli 8.0 and a project created by cordova template of Microsoft Visual Studio 2017. Thanks in advance for any suggestion.

1>MSBUILD : cordova-build error : FAILURE: Build failed with an exception.
1>MSBUILD : cordova-build error : * Where:


1>MSBUILD : cordova-build error : Build file 'C:\Users\gianc\source\repos\xxx\xxx\platforms\android\build.gradle' line: 255
1>MSBUILD : cordova-build error : * What went wrong:
1>MSBUILD : cordova-build error : A problem occurred evaluating root project 'android'.
1>MSBUILD : cordova-build error : > Could not get unknown property 'ANDROID_SDK_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
1>MSBUILD : cordova-build error : * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Command finished with error code 1: cmd /s /c "C:\Users\gianc\source\repos\xxx\xxx\platforms\android\gradlew.bat cdvBuildDebug -b C:\Users\gianc\source\repos\xxx\xxx\platforms\android\build.gradle -Dorg.gradle.daemon=true -Dorg.gradle.jvmargs=-Xmx2048m -Pandroid.useDeprecatedNdk=true"



------ Nuova copia nel progetto: android
1>MSBUILD : cordova-build error : (node:18040) UnhandledPromiseRejectionWarning: Error: cmd: Command failed with exit code 1 Error output:
1>MSBUILD : cordova-build error : FAILURE: Build failed with an exception.
1>MSBUILD : cordova-build error : * Where:
1>MSBUILD : cordova-build error : Build file 'C:\Users\gianc\source\repos\xxx\xxx\platforms\android\build.gradle' line: 255
1>MSBUILD : cordova-build error : * What went wrong:
1>MSBUILD : cordova-build error : A problem occurred evaluating root project 'android'.
1>MSBUILD : cordova-build error : > Could not get unknown property 'ANDROID_SDK_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
1>MSBUILD : cordova-build error : * Try:
1>MSBUILD : cordova-build error : Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
1>MSBUILD : cordova-build error : Picked up _JAVA_OPTIONS: -Xmx512M
1>MSBUILD : cordova-build error :  at ChildProcess.whenDone (C:\Users\gianc\source\repos\xxx\xxx\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
1>MSBUILD : cordova-build error :  at ChildProcess.emit (events.js:160:13)
1>MSBUILD : cordova-build error :  at maybeClose (internal/child_process.js:943:16)
1>MSBUILD : cordova-build error :  at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
1>MSBUILD : cordova-build error : (node:18040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
1>MSBUILD : cordova-build error : (node:18040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
1>Compilazione progetto "xxxx.jsproj" completata.

**Comment by Lukizzle** [comment] 2018-04-30 22:12
Hey guys, is there any workaround for this problem using cordova-android 6.3.0? I can't upgrade to cordova-android 7.0.0 because it's not supported by cordova-plugin-compat which is a dependency of various other plugins. Thanks for helping!

**Comment by Lukizzle** [comment] 2018-05-03 14:12
For me, the problem persists event with cordova cli 8 and when adding the plugin with the variable. The only thing that fixed it for me was updating the platform to cordova-android 7.0.0. However, I'm still facing issues with this update, so I would appreciate any alternative to make it work on cordova-android 6.2.1.

**Comment by peterpeterparker** [comment] 2018-05-03 14:17
@Lukizzle to be honest I don't know, look like everybody in this fields was able to solve the issue by upgrading or updating or specifying the variable. So I would spontaneously say that I see the following options (but probably someone more clever would come with better or other idea):

1. you could edit manually your local platform gradle / project.properties and add the library

      cordova.system.library.2=com.facebook.android:facebook-android-sdk:4.+

2. you could not update the plugin and revert to version facebook4 plugin v1.10.1

3. you could try to fix the problem you are facing and submit a PR to solve it

**Comment by artuska** [comment] 2018-05-07 12:37
```
Could not get unknown property 'ANDROID_SDK_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler
```

This happens when you install `cordova-plugin-facebook4` plugin.

It changes your `project.properties` file from

```
cordova.system.library.1=com.facebook.android:facebook-android-sdk:4.+
```

to

```
cordova.system.library.2=com.facebook.android:facebook-android-sdk:$ANDROID_SDK_VERSION
```

`ANDROID_SDK_VERSION` variable exists in `plugins/cordova-plugin-facebook4/config.xml`

```
<preference name="ANDROID_SDK_VERSION" default="4.+"/>
```

and in main `config.xml`:

```
<plugin name="cordova-plugin-facebook4" spec="~2.1.0">
    <variable name="APP_ID" value="150722098901852" />
    <variable name="APP_NAME" value="Balu" />
    <variable name="ANDROID_SDK_VERSION" value="4.+" />
</plugin>
```

but it does not work at all — error is still thrown.

**Comment by Moghul** [comment] 2018-05-09 12:05
For anyone else with this problem, here's what works for me
Cordova-cli 8.0.0
Cordova-android 6.3.0
cordova-plugin-facebook 2.1.0

cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication" --variable ANDROID_SDK_VERSION="4.+"
cordova platform remove android
cordova platform add android@6.3.0
cordova prepare android

**Comment by Boldonglen** [comment] 2018-05-17 13:54
Ive been though this post as well as several others I found on the internet and I still cant seem to build my ionic application for android:

Cordova-cli: 7.1.0
Cordova-android:6.3.0
cordova-plugin-facebook 2.1.0
Ionic: 3.20.0

I have tried adding and removing the package using: 

```
cordova plugin remove cordova-plugin-facebook4 --save
cordova plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456789" --variable APP_NAME="myApplication" --variable ANDROID_SDK_VERSION="4.+"
```

I have tried adding and removing android using: 

```
cordova platform remove android
cordova platform add android@6.3.0
```

I have tried lost of combinations of the the above and after running "ionic cordova run android --device" still get the error:

```
* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not get unknown property 'ANDROID_SDK_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

This is what is in my config.xml for the project:

```
<plugin name="cordova-plugin-facebook4" spec="^2.1.0">
        <variable name="APP_ID" value="123456789" />
        <variable name="APP_NAME" value="myApp" />
        <variable name="ANDROID_SDK_VERSION" value="4.+" />
    </plugin>
```

**Comment by Boldonglen** [comment] 2018-05-17 20:00
Hi @peterpeterparker I'm not sure how to fix the issue so can't send a pull request. As far as I am aware I am using the latest versions of all packages so not sure why it shouldn't be working? My cordova-android version is the same as other people's in this thread that have successfully got the plugin working so not sure why mine isn't working?

**Comment by peterpeterparker** [comment] 2018-05-18 07:18
@Boldonglen like I said you could then try to downgrade the plugin version to v1.10.1 otherwise you could also update cordova-android to a newer version which are for sure compatible

**Comment by daymonique** [comment] 2019-01-16 16:01
I had the same issue in my project (cordova 7.0), putting <variable name="FACEBOOK_ANDROID_SDK_VERSION" value="4.+" /> didn't work for me. I had to change the value of 
cordova.system.library.4=com.facebook.android:facebook-android-sdk:FACEBOOK_ANDROID_SDK_VERSION
 to 
cordova.system.library.4=com.facebook.android:facebook-android-sdk:4.14.+
in the platform/android/project.properties file.

This file is automatically generated by Android Tools, so i created a cordova hook to do it after add platform in cordova.

More info: https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/
