### ISSUE TITLE
Error com.facebook package does not exists

### ISSUE THREAD

**Issue by ihpalash** [jeduan/cordova-plugin-facebook4#137] opened 2016-02-14 15:18 UTC
In CMD my exact Steps are

```
C://source/phonegap platform add android

C://source/phonegap plugin add cordova-plugin-facebook4 --save --variable APP_ID="123456123456" --variable APP_NAME="somporko"
```

And then added App_invite code in a JS file and linked it in index.php

Then I imported android platform in android studio. It automatically added the gradle and plugin issues and fixed it. But while building I am getting error for the Facebook SDK 4 Plugin

```
Error:(8, 20) error: package com.facebook does not exist
Error:(9, 20) error: package com.facebook does not exist
Error:(10, 20) error: package com.facebook does not exist
Error:(11, 20) error: package com.facebook does not exist
Error:(12, 20) error: package com.facebook does not exist
Error:(13, 20) error: package com.facebook does not exist
Error:(14, 20) error: package com.facebook does not exist
Error:(15, 20) error: package com.facebook does not exist
Error:(16, 20) error: package com.facebook does not exist
Error:(17, 20) error: package com.facebook does not exist
Error:(18, 20) error: package com.facebook does not exist
Error:(19, 30) error: package com.facebook.appevents does not exist
Error:(20, 26) error: package com.facebook.login does not exist
Error:(21, 26) error: package com.facebook.login does not exist
Error:(22, 26) error: package com.facebook.share does not exist
Error:(23, 26) error: package com.facebook.share does not exist
Error:(24, 32) error: package com.facebook.share.model does not exist
Error:(25, 32) error: package com.facebook.share.model does not exist
Error:(26, 32) error: package com.facebook.share.model does not exist
Error:(27, 32) error: package com.facebook.share.model does not exist
Error:(28, 32) error: package com.facebook.share.model does not exist
Error:(29, 32) error: package com.facebook.share.model does not exist
Error:(30, 33) error: package com.facebook.share.widget does not exist
Error:(31, 33) error: package com.facebook.share.widget does not exist
Error:(32, 33) error: package com.facebook.share.widget does not exist
Error:(33, 33) error: package com.facebook.share.widget does not exist
Error:(69, 13) error: cannot find symbol class CallbackManager
Error:(70, 13) error: cannot find symbol class AppEventsLogger
Error:(75, 13) error: cannot find symbol class ShareDialog
Error:(76, 13) error: cannot find symbol class GameRequestDialog
Error:(77, 13) error: cannot find symbol class AppInviteDialog
Error:(78, 13) error: cannot find symbol class MessageDialog
Error:(754, 13) error: cannot find symbol class ShareLinkContent
Error:(772, 30) error: cannot find symbol class FacebookException
Error:(881, 55) error: cannot find symbol class FacebookRequestError
Error:(82, 9) error: cannot find symbol variable FacebookSdk
Error:(85, 42) error: package CallbackManager does not exist
Error:(88, 18) error: cannot find symbol variable AppEventsLogger
Error:(93, 74) error: cannot find symbol class FacebookCallback
Error:(93, 91) error: cannot find symbol class LoginResult
Error:(93, 9) error: cannot find symbol variable LoginManager
Error:(135, 27) error: cannot find symbol class ShareDialog
Error:(136, 59) error: cannot find symbol class FacebookCallback
Error:(136, 82) error: package Sharer does not exist
Error:(158, 29) error: cannot find symbol class MessageDialog
Error:(159, 61) error: cannot find symbol class FacebookCallback
Error:(159, 84) error: package Sharer does not exist
Error:(181, 33) error: cannot find symbol class GameRequestDialog
Error:(182, 65) error: cannot find symbol class FacebookCallback
Error:(182, 99) error: package GameRequestDialog does not exist
Error:(212, 31) error: cannot find symbol class AppInviteDialog
Error:(213, 63) error: cannot find symbol class FacebookCallback
Error:(213, 95) error: package AppInviteDialog does not exist
Error:(251, 9) error: cannot find symbol variable AppEventsLogger
Error:(257, 9) error: cannot find symbol variable AppEventsLogger
Error:(275, 17) error: cannot find symbol variable LoginManager
Error:(288, 41) error: cannot find symbol variable AccessToken
Error:(330, 21) error: cannot find symbol variable AppEventsLogger
Error:(373, 13) error: cannot find symbol variable AppInviteDialog
Error:(374, 29) error: package AppInviteContent does not exist
Error:(374, 68) error: package AppInviteContent does not exist
Error:(426, 18) error: cannot find symbol variable GameRequestDialog
Error:(435, 31) error: package GameRequestContent does not exist
Error:(435, 72) error: package GameRequestContent does not exist
Error:(448, 45) error: package GameRequestContent does not exist
Error:(448, 88) error: package GameRequestContent does not exist
Error:(456, 45) error: package GameRequestContent does not exist
Error:(456, 82) error: package GameRequestContent does not exist
Error:(466, 38) error: cannot find symbol class ShareLinkContent
Error:(466, 18) error: cannot find symbol variable ShareDialog
Error:(475, 13) error: cannot find symbol class ShareLinkContent
Error:(479, 38) error: cannot find symbol class ShareOpenGraphContent
Error:(479, 18) error: cannot find symbol variable ShareDialog
Error:(496, 33) error: package ShareOpenGraphObject does not exist
Error:(496, 82) error: package ShareOpenGraphObject does not exist
Error:(517, 33) error: package ShareOpenGraphAction does not exist
Error:(517, 82) error: package ShareOpenGraphAction does not exist
Error:(534, 34) error: package ShareOpenGraphContent does not exist
Error:(534, 78) error: package ShareOpenGraphContent does not exist
Error:(541, 40) error: cannot find symbol class ShareLinkContent
Error:(541, 18) error: cannot find symbol variable MessageDialog
Error:(550, 29) error: package ShareLinkContent does not exist
Error:(550, 68) error: package ShareLinkContent does not exist
Error:(590, 9) error: cannot find symbol class AccessToken
Error:(590, 35) error: cannot find symbol variable AccessToken
Error:(627, 9) error: cannot find symbol class LoginManager
Error:(627, 37) error: cannot find symbol variable LoginManager
Error:(709, 13) error: cannot find symbol variable LoginManager
Error:(747, 13) error: cannot find symbol variable LoginManager
Error:(750, 13) error: cannot find symbol variable LoginManager
Error:(755, 25) error: package ShareLinkContent does not exist
Error:(755, 64) error: package ShareLinkContent does not exist
Error:(769, 16) error: cannot find symbol variable AccessToken
Error:(779, 34) error: cannot find symbol class FacebookOperationCanceledException
Error:(782, 41) error: cannot find symbol class FacebookDialogException
Error:(804, 9) error: cannot find symbol class GraphRequest
Error:(804, 70) error: cannot find symbol variable AccessToken
Error:(804, 136) error: package GraphRequest does not exist
Error:(804, 37) error: cannot find symbol variable GraphRequest
Error:(854, 15) error: cannot find symbol class AccessToken
Error:Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 23.097 secs
Information:101 errors
Information:0 warnings
Information:See complete output in console
```

![mage of Android Studio Error](http://i.stack.imgur.com/q0xu5.png)

![no project](http://i.imgur.com/x1ZSXQr.png?1)

**Comment by dbroadhurst** [comment] 2016-02-14 15:34
I'm also seeing this issue. When I use the Chrome device debugger none of the API exists.

```
cordova plugin add cordova-plugin-facebook --save  --variable FACEBOOK_APP_ID="removed" --variable FACEBOOK_DISPLAY_NAME="removed"  
```
node v5.6.0
cordova 6.0.0

**Comment by jeduan** [comment] 2016-02-15 00:27
Did you use search? This looks like a duplicate of #128

**Comment by dbroadhurst** [comment] 2016-02-15 00:46
I've done a cordova clean and rebuilt but same issue. I'm not seeing any build issues and the .apk builds as expected I just don't have the javascript API when I inspect the device. Here's some of the build output

```
v:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV42300Library
:prepareComFacebookAndroidFacebookAndroidSdk430Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics840Library
:prepareComGoogleAndroidGmsPlayServicesBasement840Library
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues UP-TO-DATE
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJavaWithJavacNote: /Users/davidbroadhurst/dev/union25/citest/device/platforms/android/src/com/cmackay/plugins/googleanalytics/GoogleAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by dbroadhurst** [comment] 2016-02-15 02:26
I found the API @ plugins.CordovaFacebook.login but invoking login does not do anything

**Comment by dbroadhurst** [comment] 2016-02-15 15:47
Got everything working. I was upgrading from a earlier version and didn't realize so much has changed

**Comment by jeduan** [comment] 2016-02-15 16:56
Great!

**Closed by jeduan** 2016-02-15 16:56 UTC

**Comment by aeebikhan** [comment] 2017-03-15 07:39
i am facing also with the same problem, i am beginner please someone help me to fix this problem
