### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by dhelia** [jeduan/cordova-plugin-facebook4#1] opened 2015-07-15 02:58 UTC
Hi Jeduan. I had been using the facebook phonegap plugin for login on my app and it worked fine just that it would open a popup for the login instead of using the already installed facebook app on the device.  Saw that updating for SDK4 can solve this issue. Tried to rebuild the app about 4 times with your updated plugin but it crashes right after it loads. 

I have setup APP_ID, SECRET and VERSION just like the previous plugin asks. Does any of this needs to change. How can I make the facebook4 plugin work ? 

Thanks!

**Comment by jeduan** [comment] 2015-07-15 03:22
I need more information to be able to help you, what device is this? Do you have any stack trace of the crashes?

**Comment by jeduan** [comment] 2015-08-10 21:59
Closing since I could not have a way to reproduce this. Please open a new issue if the problem persists.

**Closed by jeduan** 2015-08-10 21:59 UTC
